const GET_POKEMONS = 'GET_POKEMONS';
const GET_POKEMON_ID = 'GET_POKEMON_ID';
const CLEAN_DETAIL = 'CLEAN_DETAIL';
const GET_POKEMON_NAME = 'GET_POKEMON_NAME';
const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';
const ORDER_ABC = 'ORDER_ABC';
const ORDER_ATTACK = 'ORDER_ATTACK';
const RESET = 'RESET'
 
export {
    GET_POKEMONS,
    GET_POKEMON_ID,
    CLEAN_DETAIL,
    GET_POKEMON_NAME,
    FILTER_BY_TYPE,
    FILTER_BY_ORIGIN,
    ORDER_ABC,
    ORDER_ATTACK,
    RESET
}